*
* Patch Offset Table
*

	dc.b	$00,$01		; Offset to patch #0: 256
	dc.b	$27,$01		; Offset to patch #1: 295
	dc.b	$4E,$01		; Offset to patch #2: 334
	dc.b	$75,$01		; Offset to patch #3: 373
	dc.b	$9C,$01		; Offset to patch #4: 412
	dc.b	$C3,$01		; Offset to patch #5: 451
	dc.b	$EA,$01		; Offset to patch #6: 490
	dc.b	$11,$02		; Offset to patch #7: 529
	dc.b	$38,$02		; Offset to patch #8: 568
	dc.b	$5F,$02		; Offset to patch #9: 607
	dc.b	$86,$02		; Offset to patch #10: 646
	dc.b	$AD,$02		; Offset to patch #11: 685
	dc.b	$D4,$02		; Offset to patch #12: 724
	dc.b	$FB,$02		; Offset to patch #13: 763
	dc.b	$22,$03		; Offset to patch #14: 802
	dc.b	$49,$03		; Offset to patch #15: 841
	dc.b	$4A,$03		; Offset to patch #16: 842
	dc.b	$71,$03		; Offset to patch #17: 881
	dc.b	$98,$03		; Offset to patch #18: 920
	dc.b	$BF,$03		; Offset to patch #19: 959
	dc.b	$E6,$03		; Offset to patch #20: 998
	dc.b	$0D,$04		; Offset to patch #21: 1037
	dc.b	$34,$04		; Offset to patch #22: 1076
	dc.b	$5B,$04		; Offset to patch #23: 1115
	dc.b	$82,$04		; Offset to patch #24: 1154
	dc.b	$A9,$04		; Offset to patch #25: 1193
	dc.b	$D0,$04		; Offset to patch #26: 1232
	dc.b	$F7,$04		; Offset to patch #27: 1271
	dc.b	$1E,$05		; Offset to patch #28: 1310
	dc.b	$45,$05		; Offset to patch #29: 1349
	dc.b	$6C,$05		; Offset to patch #30: 1388
	dc.b	$93,$05		; Offset to patch #31: 1427
	dc.b	$BA,$05		; Offset to patch #32: 1466
	dc.b	$E1,$05		; Offset to patch #33: 1505
	dc.b	$08,$06		; Offset to patch #34: 1544
	dc.b	$2F,$06		; Offset to patch #35: 1583
	dc.b	$56,$06		; Offset to patch #36: 1622
	dc.b	$7D,$06		; Offset to patch #37: 1661
	dc.b	$A4,$06		; Offset to patch #38: 1700
	dc.b	$CB,$06		; Offset to patch #39: 1739
	dc.b	$F2,$06		; Offset to patch #40: 1778
	dc.b	$19,$07		; Offset to patch #41: 1817
	dc.b	$40,$07		; Offset to patch #42: 1856
	dc.b	$67,$07		; Offset to patch #43: 1895
	dc.b	$8E,$07		; Offset to patch #44: 1934
	dc.b	$B5,$07		; Offset to patch #45: 1973
	dc.b	$DC,$07		; Offset to patch #46: 2012
	dc.b	$03,$08		; Offset to patch #47: 2051
	dc.b	$2A,$08		; Offset to patch #48: 2090
	dc.b	$51,$08		; Offset to patch #49: 2129
	dc.b	$78,$08		; Offset to patch #50: 2168
	dc.b	$9F,$08		; Offset to patch #51: 2207
	dc.b	$C6,$08		; Offset to patch #52: 2246
	dc.b	$ED,$08		; Offset to patch #53: 2285
	dc.b	$14,$09		; Offset to patch #54: 2324
	dc.b	$3B,$09		; Offset to patch #55: 2363
	dc.b	$62,$09		; Offset to patch #56: 2402
	dc.b	$89,$09		; Offset to patch #57: 2441
	dc.b	$B0,$09		; Offset to patch #58: 2480
	dc.b	$D7,$09		; Offset to patch #59: 2519
	dc.b	$FE,$09		; Offset to patch #60: 2558
	dc.b	$25,$0A		; Offset to patch #61: 2597
	dc.b	$4C,$0A		; Offset to patch #62: 2636
	dc.b	$73,$0A		; Offset to patch #63: 2675
	dc.b	$9A,$0A		; Offset to patch #64: 2714
	dc.b	$C1,$0A		; Offset to patch #65: 2753
	dc.b	$E8,$0A		; Offset to patch #66: 2792
	dc.b	$0F,$0B		; Offset to patch #67: 2831
	dc.b	$36,$0B		; Offset to patch #68: 2870
	dc.b	$5D,$0B		; Offset to patch #69: 2909
	dc.b	$84,$0B		; Offset to patch #70: 2948
	dc.b	$AB,$0B		; Offset to patch #71: 2987
	dc.b	$D2,$0B		; Offset to patch #72: 3026
	dc.b	$F9,$0B		; Offset to patch #73: 3065
	dc.b	$20,$0C		; Offset to patch #74: 3104
	dc.b	$47,$0C		; Offset to patch #75: 3143
	dc.b	$6E,$0C		; Offset to patch #76: 3182
	dc.b	$95,$0C		; Offset to patch #77: 3221
	dc.b	$BC,$0C		; Offset to patch #78: 3260
	dc.b	$BD,$0C		; Offset to patch #79: 3261
	dc.b	$E4,$0C		; Offset to patch #80: 3300
	dc.b	$0B,$0D		; Offset to patch #81: 3339
	dc.b	$32,$0D		; Offset to patch #82: 3378
	dc.b	$59,$0D		; Offset to patch #83: 3417
	dc.b	$80,$0D		; Offset to patch #84: 3456
	dc.b	$A7,$0D		; Offset to patch #85: 3495
	dc.b	$CE,$0D		; Offset to patch #86: 3534
	dc.b	$F5,$0D		; Offset to patch #87: 3573
	dc.b	$1C,$0E		; Offset to patch #88: 3612
	dc.b	$43,$0E		; Offset to patch #89: 3651
	dc.b	$6A,$0E		; Offset to patch #90: 3690
	dc.b	$91,$0E		; Offset to patch #91: 3729
	dc.b	$B8,$0E		; Offset to patch #92: 3768
	dc.b	$DF,$0E		; Offset to patch #93: 3807
	dc.b	$06,$0F		; Offset to patch #94: 3846
	dc.b	$2D,$0F		; Offset to patch #95: 3885
	dc.b	$54,$0F		; Offset to patch #96: 3924
	dc.b	$7B,$0F		; Offset to patch #97: 3963
	dc.b	$A2,$0F		; Offset to patch #98: 4002
	dc.b	$C9,$0F		; Offset to patch #99: 4041
	dc.b	$F0,$0F		; Offset to patch #100: 4080
	dc.b	$17,$10		; Offset to patch #101: 4119
	dc.b	$3E,$10		; Offset to patch #102: 4158
	dc.b	$65,$10		; Offset to patch #103: 4197
	dc.b	$8C,$10		; Offset to patch #104: 4236
	dc.b	$B3,$10		; Offset to patch #105: 4275
	dc.b	$DA,$10		; Offset to patch #106: 4314
	dc.b	$01,$11		; Offset to patch #107: 4353
	dc.b	$28,$11		; Offset to patch #108: 4392
	dc.b	$2F,$11		; Offset to patch #109: 4399
	dc.b	$36,$11		; Offset to patch #110: 4406
	dc.b	$5D,$11		; Offset to patch #111: 4445
	dc.b	$84,$11		; Offset to patch #112: 4484
	dc.b	$AB,$11		; Offset to patch #113: 4523
	dc.b	$D2,$11		; Offset to patch #114: 4562
	dc.b	$F9,$11		; Offset to patch #115: 4601
	dc.b	$20,$12		; Offset to patch #116: 4640
	dc.b	$47,$12		; Offset to patch #117: 4679
	dc.b	$6E,$12		; Offset to patch #118: 4718
	dc.b	$95,$12		; Offset to patch #119: 4757
	dc.b	$BC,$12		; Offset to patch #120: 4796
	dc.b	$E3,$12		; Offset to patch #121: 4835
	dc.b	$0A,$13		; Offset to patch #122: 4874
	dc.b	$31,$13		; Offset to patch #123: 4913
	dc.b	$58,$13		; Offset to patch #124: 4952
	dc.b	$7F,$13		; Offset to patch #125: 4991
	dc.b	$86,$13		; Offset to patch #126: 4998
	dc.b	$8D,$13		; Offset to patch #127: 5005
*
* Patch Data
*

* Patch 0 "Big Explosion": FM
	dc.b	0
	dc.b	$00,$00,$3C,$C0,$78,$00,$1F,$00
	dc.b	$04,$03,$30,$00,$14,$00,$0E,$04
	dc.b	$30,$06,$0F,$00,$08,$07,$70,$05
	dc.b	$1F,$06,$04,$09,$00,$00,$00,$00
	dc.b	$00,$00,$00,$00,$0F,$00
* Patch 1 "Button Tick": FM
	dc.b	0
	dc.b	$00,$00,$3C,$C0,$04,$15,$15,$00
	dc.b	$11,$0A,$04,$16,$1F,$0D,$15,$6A
	dc.b	$0E,$00,$1F,$15,$00,$BF,$00,$0D
	dc.b	$1F,$11,$1F,$FD,$00,$00,$00,$00
	dc.b	$00,$00,$00,$00,$0F,$00
* Patch 2 "Left Missle": FM
	dc.b	0
	dc.b	$00,$00,$3C,$80,$78,$08,$1A,$00
	dc.b	$07,$00,$00,$03,$0D,$11,$0A,$04
	dc.b	$30,$05,$0F,$00,$08,$08,$70,$00
	dc.b	$0B,$06,$0B,$0A,$00,$00,$00,$00
	dc.b	$00,$00,$00,$00,$03,$00
* Patch 3 "Hooray 1 L": FM
	dc.b	0
	dc.b	$00,$00,$11,$80,$00,$14,$19,$09
	dc.b	$03,$30,$05,$0C,$1F,$13,$0E,$16
	dc.b	$03,$0F,$14,$08,$0F,$74,$00,$00
	dc.b	$1E,$0C,$00,$58,$00,$00,$00,$00
	dc.b	$00,$00,$00,$00,$0F,$00
* Patch 4 "Hooray 1 R": FM
	dc.b	0
	dc.b	$00,$00,$11,$40,$02,$11,$19,$09
	dc.b	$03,$30,$05,$0C,$1F,$13,$0E,$16
	dc.b	$03,$0F,$14,$08,$0F,$74,$00,$00
	dc.b	$1E,$0C,$00,$58,$00,$00,$00,$00
	dc.b	$00,$00,$00,$00,$0F,$00
* Patch 5 "Hooray 2 L": FM
	dc.b	0
	dc.b	$00,$00,$2C,$80,$00,$01,$1A,$00
	dc.b	$07,$0F,$00,$00,$11,$0D,$0A,$09
	dc.b	$0E,$00,$1B,$00,$00,$0B,$00,$01
	dc.b	$1F,$00,$14,$38,$00,$00,$00,$00
	dc.b	$00,$00,$00,$00,$0F,$00
* Patch 6 "Hooray 2 R": FM
	dc.b	0
	dc.b	$00,$00,$24,$40,$01,$01,$1A,$00
	dc.b	$07,$0F,$01,$00,$11,$0D,$0A,$09
	dc.b	$0E,$00,$13,$00,$00,$0D,$00,$01
	dc.b	$17,$00,$14,$38,$00,$00,$00,$00
	dc.b	$00,$00,$00,$00,$0F,$00
* Patch 7 "Hooray 2 C": FM
	dc.b	0
	dc.b	$00,$00,$1C,$C0,$00,$00,$1B,$00
	dc.b	$03,$40,$01,$07,$13,$00,$07,$00
	dc.b	$00,$00,$1C,$00,$05,$0D,$00,$00
	dc.b	$09,$00,$02,$0B,$00,$00,$00,$00
	dc.b	$00,$00,$00,$00,$0F,$00
* Patch 8 "Beam In 1": FM
	dc.b	0
	dc.b	$0E,$00,$04,$F0,$00,$12,$09,$80
	dc.b	$04,$08,$36,$0A,$05,$00,$05,$03
	dc.b	$01,$06,$06,$84,$02,$39,$03,$0C
	dc.b	$07,$00,$03,$09,$00,$00,$00,$00
	dc.b	$00,$00,$00,$00,$0F,$00
* Patch 9 "Beam In 2": FM
	dc.b	0
	dc.b	$0E,$00,$04,$F0,$04,$0E,$0A,$80
	dc.b	$04,$08,$31,$01,$18,$00,$09,$08
	dc.b	$02,$00,$0D,$82,$06,$39,$01,$02
	dc.b	$0C,$0B,$08,$49,$00,$00,$00,$00
	dc.b	$00,$00,$00,$00,$0F,$00
* Patch 10 "Too Bad L": FM
	dc.b	0
	dc.b	$00,$00,$2C,$80,$00,$01,$1A,$00
	dc.b	$07,$0F,$00,$00,$11,$0D,$0A,$09
	dc.b	$0E,$00,$1B,$00,$00,$0B,$00,$01
	dc.b	$1F,$00,$14,$38,$00,$00,$00,$00
	dc.b	$00,$00,$00,$00,$0F,$00
* Patch 11 "Too Bad R": FM
	dc.b	0
	dc.b	$00,$00,$24,$40,$01,$01,$1A,$00
	dc.b	$07,$0F,$01,$00,$11,$0D,$0A,$09
	dc.b	$0E,$00,$13,$00,$00,$0D,$00,$01
	dc.b	$17,$00,$14,$38,$00,$00,$00,$00
	dc.b	$00,$00,$00,$00,$0F,$00
* Patch 12 "Too Bad C": FM
	dc.b	0
	dc.b	$00,$00,$1C,$C0,$00,$00,$1B,$00
	dc.b	$03,$40,$01,$07,$13,$00,$07,$00
	dc.b	$00,$00,$1C,$00,$08,$0D,$00,$00
	dc.b	$09,$00,$06,$0B,$00,$00,$00,$00
	dc.b	$00,$00,$00,$00,$0F,$00
* Patch 13 "Thud on Metal": FM
	dc.b	0
	dc.b	$00,$00,$3B,$C0,$72,$00,$1F,$07
	dc.b	$06,$08,$30,$00,$94,$06,$0C,$08
	dc.b	$35,$06,$0F,$05,$0A,$07,$71,$00
	dc.b	$1F,$06,$05,$07,$00,$00,$00,$00
	dc.b	$00,$00,$00,$00,$0E,$00
* Patch 14 "Right Missle": FM
	dc.b	0
	dc.b	$00,$00,$3C,$40,$78,$08,$1A,$00
	dc.b	$07,$00,$00,$03,$0D,$11,$0A,$04
	dc.b	$30,$05,$0F,$00,$08,$08,$70,$00
	dc.b	$0B,$06,$0B,$0A,$00,$00,$00,$00
	dc.b	$00,$00,$00,$00,$03,$00
* Patch 15 "<Unused #15>": Unknown Type!
	dc.b	99		; unknown/undefined patch type
* Patch 16 "Cello-soft attack": FM
	dc.b	0
	dc.b	$09,$00,$32,$D2,$30,$22,$1C,$04
	dc.b	$00,$16,$71,$30,$15,$09,$03,$04
	dc.b	$34,$22,$11,$10,$00,$0B,$01,$0A
	dc.b	$8B,$0A,$02,$1A,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 17 "Contrabass-soft attack": FM
	dc.b	0
	dc.b	$09,$00,$12,$D2,$30,$17,$14,$04
	dc.b	$00,$06,$01,$22,$12,$01,$03,$04
	dc.b	$33,$25,$98,$0A,$00,$0B,$00,$0D
	dc.b	$4B,$8A,$00,$0A,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 18 "Thin Solo Violin": FM
	dc.b	0
	dc.b	$09,$00,$14,$D1,$21,$03,$C8,$01
	dc.b	$00,$08,$33,$23,$CB,$81,$00,$2A
	dc.b	$21,$1C,$88,$05,$03,$28,$11,$12
	dc.b	$C3,$15,$00,$0F,$20,$05,$0C,$03
	dc.b	$1F,$CB,$1F,$DA,$0F,$00
* Patch 19 "Solo violin-swell": FM
	dc.b	0
	dc.b	$09,$00,$14,$D2,$21,$0F,$C8,$01
	dc.b	$00,$08,$33,$1E,$CB,$81,$00,$2A
	dc.b	$21,$17,$43,$06,$00,$08,$11,$12
	dc.b	$43,$15,$00,$08,$20,$05,$0C,$03
	dc.b	$1F,$CB,$1F,$DA,$0F,$00
* Patch 20 "Cello/Bass-swell": FM
	dc.b	0
	dc.b	$09,$00,$14,$E1,$30,$14,$C8,$01
	dc.b	$00,$08,$30,$1F,$CB,$01,$00,$2A
	dc.b	$01,$1C,$83,$06,$00,$08,$01,$12
	dc.b	$84,$15,$00,$08,$20,$05,$0C,$03
	dc.b	$1F,$CB,$1F,$DA,$0F,$00
* Patch 21 "Quick Strings": FM
	dc.b	0
	dc.b	$09,$00,$2C,$D2,$22,$17,$D2,$05
	dc.b	$00,$48,$33,$1A,$57,$09,$00,$3F
	dc.b	$20,$13,$8E,$05,$00,$2F,$11,$15
	dc.b	$88,$95,$00,$0F,$20,$05,$0C,$03
	dc.b	$1F,$CB,$1F,$DA,$0F,$00
* Patch 22 "Section Strings": FM
	dc.b	0
	dc.b	$0B,$00,$3B,$63,$33,$17,$1E,$18
	dc.b	$0C,$68,$30,$11,$14,$1C,$05,$24
	dc.b	$72,$19,$13,$1F,$06,$38,$00,$08
	dc.b	$0F,$01,$1F,$A6,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0E,$00
* Patch 23 "Synth Strings": FM
	dc.b	0
	dc.b	$09,$00,$1C,$C3,$20,$17,$0F,$01
	dc.b	$00,$2F,$11,$1E,$08,$09,$00,$0F
	dc.b	$11,$21,$0E,$85,$02,$0F,$04,$1D
	dc.b	$06,$95,$03,$0F,$20,$05,$0C,$03
	dc.b	$1F,$CB,$1F,$DA,$0F,$00
* Patch 24 "Solo Pizzicato": FM
	dc.b	0
	dc.b	$0A,$00,$1A,$C4,$33,$1C,$54,$17
	dc.b	$08,$8A,$31,$00,$5B,$1B,$06,$AB
	dc.b	$04,$05,$58,$17,$05,$BB,$01,$06
	dc.b	$14,$12,$16,$6C,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 25 "Pizzicato-Octaves": FM
	dc.b	0
	dc.b	$0A,$00,$2D,$C4,$02,$1A,$94,$17
	dc.b	$08,$8A,$30,$0C,$58,$0D,$16,$9B
	dc.b	$12,$0B,$58,$11,$05,$BB,$02,$03
	dc.b	$14,$19,$16,$7C,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 26 "Trumpet-bright": FM
	dc.b	0
	dc.b	$0A,$00,$3D,$D2,$21,$1F,$8F,$05
	dc.b	$01,$E7,$21,$21,$8C,$00,$02,$17
	dc.b	$32,$18,$9B,$0B,$02,$46,$33,$0E
	dc.b	$94,$80,$02,$08,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 27 "Trombone-bright": FM
	dc.b	0
	dc.b	$0B,$00,$3D,$D2,$00,$1C,$88,$06
	dc.b	$01,$67,$01,$0A,$8F,$0D,$0A,$2F
	dc.b	$00,$0B,$97,$87,$02,$1F,$51,$17
	dc.b	$99,$87,$00,$1F,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 28 "Trumpet-dark": FM
	dc.b	0
	dc.b	$09,$00,$32,$D2,$01,$1F,$8E,$1F
	dc.b	$01,$67,$01,$1E,$8A,$09,$00,$27
	dc.b	$01,$1B,$97,$13,$02,$46,$01,$03
	dc.b	$8E,$87,$00,$18,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 29 "Trombone-dark": FM
	dc.b	0
	dc.b	$09,$00,$2D,$E2,$00,$1A,$8C,$0D
	dc.b	$01,$27,$00,$1B,$8A,$08,$00,$27
	dc.b	$00,$0F,$97,$87,$02,$16,$51,$06
	dc.b	$97,$87,$00,$18,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 30 "Tuba ": FM
	dc.b	0
	dc.b	$0C,$00,$0B,$D1,$71,$2F,$07,$0A
	dc.b	$18,$2F,$71,$1A,$8A,$0B,$0C,$0F
	dc.b	$00,$1B,$CD,$90,$03,$28,$40,$00
	dc.b	$4E,$00,$00,$05,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 31 "Section Trumpets": FM
	dc.b	0
	dc.b	$0A,$00,$35,$D2,$21,$17,$8E,$00
	dc.b	$01,$47,$20,$13,$95,$00,$02,$17
	dc.b	$31,$0B,$9B,$05,$02,$36,$14,$0D
	dc.b	$94,$80,$02,$08,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 32 "Section Trombones": FM
	dc.b	0
	dc.b	$09,$00,$1C,$E2,$00,$16,$8C,$0D
	dc.b	$01,$27,$01,$19,$8A,$08,$00,$27
	dc.b	$01,$09,$97,$87,$02,$16,$21,$18
	dc.b	$97,$81,$00,$18,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 33 "Sect.Trumpets-overblown": FM
	dc.b	0
	dc.b	$0A,$00,$35,$D2,$22,$15,$8E,$00
	dc.b	$01,$07,$21,$1A,$8C,$00,$02,$17
	dc.b	$32,$18,$9B,$05,$02,$36,$34,$0C
	dc.b	$94,$80,$02,$08,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 34 "Muted Brass": FM
	dc.b	0
	dc.b	$09,$00,$3A,$D2,$07,$1D,$4D,$0C
	dc.b	$01,$27,$02,$1E,$92,$05,$0A,$57
	dc.b	$02,$20,$97,$13,$02,$46,$01,$08
	dc.b	$95,$87,$00,$18,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0D,$00
* Patch 35 "Synth Brass": FM
	dc.b	0
	dc.b	$0A,$00,$35,$D2,$21,$1A,$8E,$00
	dc.b	$01,$07,$21,$16,$8C,$00,$02,$17
	dc.b	$32,$1A,$9B,$05,$02,$36,$33,$10
	dc.b	$94,$80,$02,$08,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 36 "Piano ": FM
	dc.b	0
	dc.b	$00,$00,$12,$C0,$01,$25,$58,$07
	dc.b	$04,$71,$64,$3A,$56,$09,$1F,$6B
	dc.b	$71,$11,$DF,$17,$0F,$91,$31,$0D
	dc.b	$99,$07,$02,$6A,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 37 "Harpsichord ": FM
	dc.b	0
	dc.b	$07,$00,$2A,$E0,$01,$19,$5F,$0A
	dc.b	$02,$81,$03,$23,$5F,$05,$02,$51
	dc.b	$7C,$1F,$9F,$0B,$02,$31,$32,$11
	dc.b	$94,$08,$02,$AB,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 38 "Pipe Organ-full": FM
	dc.b	0
	dc.b	$0B,$00,$04,$D0,$01,$29,$1F,$0A
	dc.b	$00,$0F,$07,$25,$9D,$00,$18,$47
	dc.b	$73,$0F,$0E,$00,$00,$DB,$01,$11
	dc.b	$13,$98,$09,$0F,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 39 "Pipe Organ-1/2stop": FM
	dc.b	0
	dc.b	$0B,$00,$04,$D0,$01,$29,$1F,$0A
	dc.b	$00,$0F,$01,$1B,$9D,$00,$18,$47
	dc.b	$73,$1A,$0E,$00,$00,$DB,$01,$12
	dc.b	$13,$98,$00,$0F,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 40 "Celesta ": FM
	dc.b	0
	dc.b	$09,$00,$00,$F0,$13,$08,$53,$01
	dc.b	$1B,$40,$3B,$22,$1D,$0F,$1F,$F3
	dc.b	$71,$11,$5B,$03,$1D,$03,$71,$12
	dc.b	$1F,$00,$0D,$0F,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 41 "B3 Organ ": FM
	dc.b	0
	dc.b	$0C,$00,$27,$E4,$33,$0C,$5F,$8B
	dc.b	$01,$8B,$03,$18,$1A,$9D,$00,$2A
	dc.b	$72,$13,$1C,$1F,$00,$1A,$01,$12
	dc.b	$5B,$9C,$00,$0F,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 42 "Vibrato Organ ": FM
	dc.b	0
	dc.b	$0B,$00,$3C,$B5,$05,$20,$19,$98
	dc.b	$00,$8F,$32,$16,$57,$8C,$0A,$1C
	dc.b	$55,$13,$5A,$8C,$04,$1F,$31,$11
	dc.b	$5C,$8B,$01,$1F,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 43 "Rhodes Piano ": FM
	dc.b	0
	dc.b	$00,$00,$02,$C0,$21,$29,$0F,$01
	dc.b	$02,$01,$02,$2C,$8F,$03,$14,$21
	dc.b	$72,$23,$D0,$06,$1A,$71,$31,$0D
	dc.b	$54,$08,$1C,$8A,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 44 "Electric Piano-bright": FM
	dc.b	0
	dc.b	$0A,$00,$3C,$E1,$24,$22,$59,$0A
	dc.b	$00,$BA,$51,$12,$5F,$0A,$02,$79
	dc.b	$21,$15,$58,$89,$02,$AB,$50,$14
	dc.b	$57,$0B,$02,$3F,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 45 "Electric Piano-dark": FM
	dc.b	0
	dc.b	$0B,$00,$23,$C0,$03,$20,$12,$18
	dc.b	$0C,$69,$02,$18,$1A,$1C,$0C,$38
	dc.b	$01,$1D,$1A,$1F,$0B,$39,$01,$0B
	dc.b	$1E,$11,$09,$29,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 46 "Nasty Clav ": FM
	dc.b	0
	dc.b	$06,$00,$0D,$C5,$10,$02,$DF,$00
	dc.b	$11,$85,$22,$0E,$9F,$04,$13,$48
	dc.b	$32,$08,$DF,$09,$1E,$88,$00,$0A
	dc.b	$DF,$03,$1A,$68,$1F,$35,$3F,$B7
	dc.b	$3F,$B6,$3F,$70,$0F,$00
* Patch 47 "Harp": FM
	dc.b	0
	dc.b	$0B,$00,$2C,$41,$36,$04,$D0,$1C
	dc.b	$0D,$6F,$62,$2E,$4C,$97,$17,$FB
	dc.b	$72,$06,$CF,$0B,$0C,$4B,$22,$10
	dc.b	$56,$87,$13,$AF,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 48 "Muted Synth Organ": FM
	dc.b	0
	dc.b	$0A,$00,$24,$93,$03,$19,$17,$81
	dc.b	$0C,$9F,$32,$15,$18,$81,$0B,$6C
	dc.b	$02,$0D,$0D,$8C,$0B,$5F,$02,$14
	dc.b	$12,$8B,$01,$1F,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0D,$00
* Patch 49 "Analog Pad ": FM
	dc.b	0
	dc.b	$09,$00,$13,$C2,$52,$14,$02,$87
	dc.b	$00,$0C,$51,$17,$86,$0C,$00,$1C
	dc.b	$14,$2C,$12,$82,$00,$1C,$11,$19
	dc.b	$0C,$10,$00,$0C,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 50 "Synth Vox": FM
	dc.b	0
	dc.b	$0A,$00,$1D,$E3,$31,$32,$0E,$01
	dc.b	$01,$4C,$32,$19,$12,$0C,$04,$1C
	dc.b	$03,$1F,$12,$85,$03,$1C,$02,$24
	dc.b	$11,$10,$03,$0C,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 51 "FM Shimmer ": FM
	dc.b	0
	dc.b	$0A,$00,$25,$F3,$72,$00,$01,$97
	dc.b	$00,$0F,$74,$0F,$56,$9B,$03,$3F
	dc.b	$03,$0F,$14,$9D,$05,$3F,$32,$11
	dc.b	$17,$99,$02,$3F,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 52 "Percussive Synth": FM
	dc.b	0
	dc.b	$0B,$00,$3C,$52,$32,$0A,$D8,$1C
	dc.b	$0D,$3F,$01,$1D,$55,$94,$17,$CB
	dc.b	$72,$05,$DA,$0B,$0C,$4B,$21,$07
	dc.b	$5B,$87,$13,$AF,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 53 "Prophet ": FM
	dc.b	0
	dc.b	$0A,$00,$1F,$C7,$33,$14,$03,$81
	dc.b	$15,$48,$01,$18,$04,$81,$0C,$38
	dc.b	$52,$16,$03,$81,$0F,$38,$21,$18
	dc.b	$86,$81,$0F,$38,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 54 "Analog Solo": FM
	dc.b	0
	dc.b	$09,$00,$04,$81,$01,$11,$53,$8D
	dc.b	$09,$69,$01,$1D,$81,$93,$02,$08
	dc.b	$72,$0B,$1E,$85,$00,$48,$61,$09
	dc.b	$1F,$07,$00,$08,$31,$3B,$2B,$78
	dc.b	$08,$4E,$33,$00,$0F,$00
* Patch 55 "Backwards Synth ": FM
	dc.b	0
	dc.b	$0F,$00,$2C,$D5,$15,$12,$91,$06
	dc.b	$0F,$D0,$65,$23,$1F,$88,$04,$1F
	dc.b	$71,$07,$10,$81,$07,$0F,$01,$14
	dc.b	$10,$00,$08,$0F,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 56 "Digital Solo": FM
	dc.b	0
	dc.b	$0A,$00,$3C,$D4,$22,$1E,$8F,$01
	dc.b	$08,$47,$2B,$17,$9F,$07,$13,$B5
	dc.b	$32,$11,$95,$80,$02,$17,$33,$0C
	dc.b	$1F,$8D,$0C,$97,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 57 "Steel String Guitar": FM
	dc.b	0
	dc.b	$0C,$00,$22,$C0,$31,$1D,$D8,$00
	dc.b	$0B,$5C,$14,$32,$D3,$00,$14,$B4
	dc.b	$3A,$1A,$D6,$08,$00,$2F,$01,$0D
	dc.b	$96,$07,$06,$29,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 58 "Nylon String Guitar ": FM
	dc.b	0
	dc.b	$09,$00,$00,$F2,$73,$1A,$53,$01
	dc.b	$1B,$40,$33,$15,$14,$0F,$1F,$F3
	dc.b	$75,$21,$19,$0D,$18,$03,$71,$0A
	dc.b	$1A,$00,$0A,$0D,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 59 "Chorused Strat": FM
	dc.b	0
	dc.b	$0A,$00,$12,$D3,$31,$1D,$D8,$00
	dc.b	$0B,$5C,$12,$29,$D3,$00,$14,$B4
	dc.b	$37,$1A,$D6,$08,$00,$2F,$02,$0C
	dc.b	$96,$87,$06,$29,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 60 "Jazz Guitar": FM
	dc.b	0
	dc.b	$0C,$00,$12,$C0,$31,$20,$D8,$00
	dc.b	$0B,$5C,$11,$32,$D5,$05,$14,$34
	dc.b	$31,$10,$D6,$08,$00,$2F,$00,$09
	dc.b	$96,$07,$06,$29,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 61 "Muted Pick": FM
	dc.b	0
	dc.b	$0B,$00,$2C,$41,$33,$04,$D0,$1C
	dc.b	$0D,$6F,$61,$2E,$4C,$97,$17,$FB
	dc.b	$71,$06,$CF,$11,$0C,$AB,$21,$02
	dc.b	$56,$9F,$13,$AF,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 62 "Psychedelic Guitar": FM
	dc.b	0
	dc.b	$0B,$00,$3C,$C0,$21,$1D,$19,$0A
	dc.b	$00,$BA,$56,$19,$59,$09,$0C,$AF
	dc.b	$25,$11,$18,$00,$06,$AB,$5C,$14
	dc.b	$5C,$07,$19,$AF,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 63 "Heavy Metal/Feedback": FM
	dc.b	0
	dc.b	$08,$00,$3D,$D2,$02,$15,$96,$01
	dc.b	$03,$3F,$03,$0C,$1A,$01,$01,$2F
	dc.b	$12,$02,$D8,$06,$01,$0F,$61,$02
	dc.b	$15,$83,$0D,$0F,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 64 "Two Hand Tap ": FM
	dc.b	0
	dc.b	$0B,$00,$39,$43,$01,$20,$5E,$80
	dc.b	$00,$16,$01,$20,$5F,$12,$03,$0E
	dc.b	$01,$21,$15,$04,$03,$0F,$01,$01
	dc.b	$1F,$04,$00,$0F,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 65 "Vibes\Organ ": FM
	dc.b	0
	dc.b	$0B,$00,$3E,$D4,$09,$33,$1E,$0B
	dc.b	$06,$AB,$00,$0E,$1F,$06,$06,$4B
	dc.b	$72,$11,$13,$0A,$06,$7B,$01,$16
	dc.b	$13,$0A,$06,$7B,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$00,$00,$0F,$00
* Patch 66 "Clarinet/Xylophone": FM
	dc.b	0
	dc.b	$08,$00,$26,$E3,$12,$1C,$91,$08
	dc.b	$0B,$6F,$74,$09,$9B,$8E,$14,$F8
	dc.b	$71,$12,$13,$06,$00,$0D,$44,$01
	dc.b	$DB,$8F,$1F,$F8,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 67 "Trumpet/Xylophone": FM
	dc.b	0
	dc.b	$0A,$00,$3E,$D2,$31,$11,$8C,$1F
	dc.b	$04,$37,$60,$06,$93,$0E,$03,$37
	dc.b	$31,$0B,$91,$08,$01,$38,$32,$06
	dc.b	$93,$9A,$00,$98,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 68 "Analog Synth Bass": FM
	dc.b	0
	dc.b	$0A,$00,$1D,$D0,$01,$12,$1F,$8A
	dc.b	$00,$9F,$22,$09,$14,$01,$00,$1F
	dc.b	$33,$09,$50,$0D,$0C,$3D,$00,$08
	dc.b	$11,$1B,$00,$2D,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 69 "Mini Moog ": FM
	dc.b	0
	dc.b	$0A,$00,$24,$D4,$00,$0A,$9F,$04
	dc.b	$0D,$78,$31,$0C,$DF,$07,$1F,$BF
	dc.b	$71,$07,$5F,$02,$05,$48,$00,$0A
	dc.b	$5F,$09,$00,$1F,$3F,$FF,$3F,$FF
	dc.b	$3F,$FF,$00,$00,$0F,$00
* Patch 70 "Rap Bass ": FM
	dc.b	0
	dc.b	$0C,$00,$09,$C4,$00,$27,$1F,$09
	dc.b	$07,$08,$50,$1D,$5B,$11,$00,$F8
	dc.b	$00,$11,$5A,$09,$00,$F8,$61,$00
	dc.b	$5F,$09,$00,$3A,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 71 "Forest bass": FM
	dc.b	0
	dc.b	$01,$00,$2A,$C0,$72,$2E,$86,$07
	dc.b	$07,$8F,$72,$26,$D6,$0A,$13,$A4
	dc.b	$32,$13,$94,$10,$07,$F8,$30,$00
	dc.b	$9F,$1E,$03,$06,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 72 "Reggae Bass ": FM
	dc.b	0
	dc.b	$0C,$00,$06,$C4,$00,$1D,$1F,$09
	dc.b	$07,$08,$50,$02,$98,$0B,$13,$E8
	dc.b	$00,$04,$5A,$09,$00,$F8,$60,$10
	dc.b	$5A,$0C,$00,$FA,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 73 "TubeBell ": FM
	dc.b	0
	dc.b	$09,$00,$0C,$E1,$23,$1D,$19,$0A
	dc.b	$00,$BA,$51,$16,$19,$14,$0C,$AF
	dc.b	$20,$0D,$18,$03,$19,$AB,$52,$04
	dc.b	$5C,$87,$19,$AF,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$07,$00
* Patch 74 "Vibes-soft ": FM
	dc.b	0
	dc.b	$09,$00,$00,$F0,$70,$14,$53,$01
	dc.b	$1B,$40,$33,$2A,$1D,$0F,$1F,$F3
	dc.b	$71,$1E,$56,$03,$19,$03,$71,$06
	dc.b	$1F,$80,$0B,$06,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0E,$00
* Patch 75 "Vibes-bright ": FM
	dc.b	0
	dc.b	$09,$00,$00,$F0,$72,$08,$53,$01
	dc.b	$1B,$40,$35,$22,$1D,$0F,$1F,$F3
	dc.b	$70,$11,$5B,$03,$1D,$03,$71,$05
	dc.b	$1F,$80,$0B,$06,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 76 "res filt drum ": FM
	dc.b	0
	dc.b	$0E,$40,$34,$F5,$22,$06,$5F,$08
	dc.b	$02,$89,$03,$01,$8D,$14,$02,$AB
	dc.b	$7D,$08,$93,$0B,$12,$BF,$31,$06
	dc.b	$9D,$1B,$0B,$3C,$07,$54,$11,$19
	dc.b	$02,$71,$3F,$BB,$0F,$00
* Patch 77 "Timpani ": FM
	dc.b	0
	dc.b	$0F,$00,$17,$F5,$11,$06,$D1,$80
	dc.b	$11,$C3,$61,$04,$19,$00,$1F,$02
	dc.b	$71,$00,$1D,$00,$18,$08,$71,$00
	dc.b	$1F,$0F,$1F,$9C,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 78 "<Unused #78>": Unknown Type!
	dc.b	99		; unknown/undefined patch type
* Patch 79 "Gong/Tam Tam ": FM
	dc.b	0
	dc.b	$0F,$00,$04,$F7,$1F,$00,$45,$01
	dc.b	$00,$0F,$70,$05,$9B,$03,$00,$50
	dc.b	$0A,$10,$4F,$01,$07,$0F,$70,$00
	dc.b	$19,$8B,$1F,$FF,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 80 "Xylophone ": FM
	dc.b	0
	dc.b	$08,$00,$04,$C0,$45,$1B,$1F,$93
	dc.b	$07,$7E,$22,$1B,$9F,$92,$04,$82
	dc.b	$31,$06,$1E,$0F,$07,$FF,$01,$11
	dc.b	$1F,$0F,$02,$FF,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 81 "Juno ": FM
	dc.b	0
	dc.b	$0A,$00,$2A,$D2,$10,$14,$DF,$0A
	dc.b	$0F,$C0,$10,$1B,$19,$80,$1F,$12
	dc.b	$00,$07,$1D,$80,$18,$00,$00,$0A
	dc.b	$1C,$00,$00,$0D,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 82 "Chimes ": FM
	dc.b	0
	dc.b	$08,$00,$14,$C0,$43,$16,$1F,$91
	dc.b	$17,$FE,$43,$13,$9F,$89,$05,$F2
	dc.b	$31,$0B,$1F,$1C,$0C,$3F,$41,$0C
	dc.b	$1F,$1F,$05,$16,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 83 "Glockenspiel ": FM
	dc.b	0
	dc.b	$08,$00,$14,$C0,$46,$0B,$1F,$81
	dc.b	$17,$FE,$44,$29,$9F,$8A,$05,$F2
	dc.b	$38,$03,$1F,$14,$14,$37,$42,$0A
	dc.b	$1F,$05,$05,$16,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 84 "Marimba ": FM
	dc.b	0
	dc.b	$0F,$00,$00,$D0,$70,$00,$40,$9D
	dc.b	$1F,$90,$63,$1F,$5D,$0F,$1F,$F3
	dc.b	$70,$00,$5F,$80,$18,$03,$70,$0A
	dc.b	$1F,$00,$0C,$0F,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0C,$00
* Patch 85 "simmons": FM
	dc.b	0
	dc.b	$0B,$00,$2A,$C5,$13,$08,$9F,$19
	dc.b	$08,$CA,$00,$0D,$5F,$13,$05,$BC
	dc.b	$36,$05,$5F,$19,$06,$AC,$02,$06
	dc.b	$5F,$0F,$11,$8C,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 86 "cowbell ": FM
	dc.b	0
	dc.b	$07,$40,$04,$F5,$11,$08,$1F,$14
	dc.b	$09,$05,$70,$19,$1F,$12,$1E,$D8
	dc.b	$01,$02,$1F,$15,$1F,$C8,$00,$0D
	dc.b	$1D,$13,$10,$F8,$2E,$E0,$3F,$CC
	dc.b	$3F,$E8,$3F,$82,$0F,$00
* Patch 87 "low tom ": FM
	dc.b	0
	dc.b	$0F,$00,$38,$F7,$70,$00,$80,$1D
	dc.b	$1F,$90,$70,$00,$9F,$00,$18,$00
	dc.b	$00,$04,$DD,$8F,$1F,$F0,$70,$00
	dc.b	$1F,$00,$0C,$0F,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0C,$00
* Patch 88 "metal drums ": FM
	dc.b	0
	dc.b	$07,$00,$03,$C0,$0F,$2D,$19,$13
	dc.b	$0D,$80,$39,$00,$1F,$15,$19,$D8
	dc.b	$00,$04,$1D,$0D,$15,$70,$30,$00
	dc.b	$1F,$11,$1F,$BA,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 89 "hi tom ": FM
	dc.b	0
	dc.b	$0C,$40,$01,$C4,$00,$1F,$19,$1C
	dc.b	$0E,$DB,$00,$09,$1F,$15,$0D,$FD
	dc.b	$00,$1C,$1F,$11,$0E,$EC,$01,$0D
	dc.b	$1F,$01,$16,$59,$1B,$58,$13,$88
	dc.b	$0F,$A0,$13,$88,$0F,$00
* Patch 90 "808 kick": FM
	dc.b	0
	dc.b	$0B,$00,$3A,$C5,$31,$09,$9F,$18
	dc.b	$11,$5B,$01,$10,$5F,$11,$05,$BB
	dc.b	$31,$1B,$5F,$13,$06,$AB,$00,$04
	dc.b	$5F,$01,$06,$2A,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 91 "brushedsnare. ": FM
	dc.b	0
	dc.b	$07,$00,$3B,$C6,$00,$00,$1F,$00
	dc.b	$00,$00,$70,$00,$12,$05,$00,$F0
	dc.b	$0E,$00,$12,$0F,$12,$E5,$30,$09
	dc.b	$1F,$11,$16,$B6,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0B,$00
* Patch 92 "thumpKick ": FM
	dc.b	0
	dc.b	$0B,$00,$2A,$C5,$10,$02,$9F,$19
	dc.b	$08,$CB,$00,$0B,$5F,$13,$05,$BB
	dc.b	$31,$0A,$5F,$19,$06,$AB,$02,$00
	dc.b	$5F,$0E,$11,$2B,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 93 "click kick(use low key ": FM
	dc.b	0
	dc.b	$0A,$00,$0B,$F6,$00,$00,$1F,$00
	dc.b	$00,$25,$00,$08,$1F,$1F,$0C,$18
	dc.b	$05,$11,$1F,$11,$10,$28,$01,$04
	dc.b	$1D,$0F,$14,$1B,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 94 "crack snr ": FM
	dc.b	0
	dc.b	$0A,$00,$3D,$F2,$00,$06,$1F,$0B
	dc.b	$09,$F8,$01,$0A,$1F,$11,$19,$97
	dc.b	$04,$00,$DF,$13,$19,$F7,$00,$0E
	dc.b	$1D,$11,$1F,$77,$1F,$E0,$1F,$EF
	dc.b	$20,$02,$1F,$FF,$0F,$00
* Patch 95 "Open hat-fat ": FM
	dc.b	0
	dc.b	$0C,$00,$31,$F5,$2F,$06,$5F,$05
	dc.b	$02,$81,$7D,$02,$99,$05,$02,$71
	dc.b	$0F,$01,$9F,$05,$02,$53,$33,$05
	dc.b	$9F,$0F,$01,$AA,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 96 "gated snare ": FM
	dc.b	0
	dc.b	$06,$00,$39,$F5,$00,$00,$1F,$00
	dc.b	$00,$05,$00,$11,$1F,$11,$10,$28
	dc.b	$00,$08,$1F,$1F,$0C,$18,$00,$00
	dc.b	$1D,$10,$10,$18,$1F,$40,$3F,$CC
	dc.b	$3F,$E8,$3F,$82,$0F,$00
* Patch 97 "Electronic Snare ": FM
	dc.b	0
	dc.b	$03,$40,$3C,$F5,$22,$00,$5F,$08
	dc.b	$02,$89,$03,$01,$8D,$14,$02,$AB
	dc.b	$7D,$08,$93,$0B,$12,$BB,$31,$0B
	dc.b	$9D,$1B,$0B,$39,$07,$54,$11,$19
	dc.b	$02,$71,$20,$BB,$0F,$00
* Patch 98 "Rimshot": FM
	dc.b	0
	dc.b	$0B,$00,$00,$C5,$00,$18,$1F,$00
	dc.b	$00,$95,$01,$07,$1F,$1F,$0C,$08
	dc.b	$00,$12,$DF,$11,$10,$28,$05,$00
	dc.b	$9D,$94,$11,$8C,$20,$19,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 99 "Bright Snare ": FM
	dc.b	0
	dc.b	$07,$00,$3B,$C6,$00,$00,$1D,$0D
	dc.b	$0D,$00,$0F,$00,$0A,$85,$12,$20
	dc.b	$7F,$00,$1F,$80,$0D,$00,$36,$00
	dc.b	$1F,$90,$1F,$AF,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 100 "Thick Hat ": FM
	dc.b	0
	dc.b	$0B,$00,$3A,$F3,$3F,$15,$1F,$8E
	dc.b	$0D,$84,$33,$00,$5F,$0A,$08,$64
	dc.b	$7F,$0F,$1F,$8E,$0D,$94,$71,$06
	dc.b	$DF,$09,$09,$2B,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$00,$00,$0F,$00
* Patch 101 "Thin Cl. Hat ": FM
	dc.b	0
	dc.b	$08,$40,$24,$C0,$3F,$08,$5F,$0F
	dc.b	$1C,$84,$1F,$00,$DC,$80,$00,$04
	dc.b	$7C,$00,$DF,$80,$10,$49,$70,$06
	dc.b	$DF,$11,$10,$49,$20,$75,$20,$5F
	dc.b	$20,$5E,$20,$00,$0F,$00
* Patch 102 "Fretless Bass ": FM
	dc.b	0
	dc.b	$0E,$00,$01,$C2,$10,$21,$16,$03
	dc.b	$07,$98,$10,$16,$54,$0A,$0A,$B8
	dc.b	$50,$21,$0B,$04,$0C,$78,$50,$09
	dc.b	$18,$01,$04,$9B,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 103 "Fretted Bass ": FM
	dc.b	0
	dc.b	$0C,$00,$12,$C0,$30,$15,$90,$05
	dc.b	$00,$09,$12,$25,$CD,$09,$12,$50
	dc.b	$33,$27,$CE,$0A,$00,$FF,$00,$07
	dc.b	$9F,$08,$0C,$4F,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 104 "NRUSH-Percussive Synt52": FM
	dc.b	0
	dc.b	$0B,$00,$3C,$92,$32,$0A,$D8,$1C
	dc.b	$0D,$3F,$01,$1D,$55,$94,$17,$CB
	dc.b	$72,$05,$DA,$0B,$0C,$4B,$21,$07
	dc.b	$5B,$87,$13,$AF,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 105 "Forest bass L": FM
	dc.b	0
	dc.b	$01,$00,$2A,$80,$72,$2E,$86,$07
	dc.b	$07,$8F,$72,$26,$D6,$0A,$13,$A4
	dc.b	$32,$13,$94,$10,$07,$F8,$30,$00
	dc.b	$9F,$1E,$03,$06,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 106 "Forest Bass R ": FM
	dc.b	0
	dc.b	$01,$00,$2A,$40,$72,$2E,$86,$07
	dc.b	$07,$8F,$72,$26,$D6,$0A,$13,$A4
	dc.b	$32,$13,$94,$10,$07,$F8,$30,$00
	dc.b	$9F,$1E,$03,$06,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 107 "Forest bass": FM
	dc.b	0
	dc.b	$01,$00,$2A,$C0,$72,$2E,$86,$07
	dc.b	$07,$8F,$72,$26,$D6,$0A,$13,$A4
	dc.b	$32,$13,$94,$10,$07,$F8,$30,$00
	dc.b	$9F,$1E,$03,$06,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 108 "NRUSH-OpenHat.PSG": PSG Noise
	dc.b	3
	dc.b	$0C,$FF,$04,$CF,$FF,$FF
* Patch 109 "NRUSG-WhipSnare.PSG": PSG Noise
	dc.b	3
	dc.b	$0C,$FF,$1F,$C0,$14,$19
* Patch 110 "NRUSH-Forest.Marimba ": FM
	dc.b	0
	dc.b	$0E,$00,$3A,$D0,$11,$06,$9F,$1D
	dc.b	$16,$F0,$53,$0D,$83,$00,$1F,$03
	dc.b	$02,$26,$9F,$00,$18,$F3,$00,$05
	dc.b	$9F,$00,$1F,$7E,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 111 "NRUSH-Analog Pad": FM
	dc.b	0
	dc.b	$09,$00,$15,$C2,$51,$14,$02,$87
	dc.b	$00,$0C,$50,$17,$86,$0C,$00,$1C
	dc.b	$14,$25,$12,$83,$00,$1C,$11,$19
	dc.b	$0C,$10,$00,$0C,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 112 "NRUSH-Quick Strings": FM
	dc.b	0
	dc.b	$09,$00,$2C,$D2,$22,$17,$D2,$05
	dc.b	$00,$48,$33,$1A,$57,$09,$00,$3F
	dc.b	$20,$13,$8E,$05,$00,$2F,$11,$15
	dc.b	$88,$95,$00,$0F,$20,$05,$0C,$03
	dc.b	$1F,$CB,$1F,$DA,$0F,$00
* Patch 113 "NRUSH-Closed Hat ": FM
	dc.b	0
	dc.b	$08,$40,$23,$C0,$3F,$06,$56,$0F
	dc.b	$1F,$3E,$1F,$00,$D3,$80,$00,$04
	dc.b	$7C,$00,$DA,$80,$10,$F9,$70,$00
	dc.b	$D5,$11,$10,$09,$20,$75,$20,$5F
	dc.b	$20,$5E,$20,$00,$0F,$00
* Patch 114 "NRUSH-Bass ": FM
	dc.b	0
	dc.b	$0C,$00,$09,$C4,$00,$27,$1F,$09
	dc.b	$07,$08,$50,$1D,$1B,$11,$00,$F8
	dc.b	$00,$11,$1A,$09,$00,$F8,$61,$00
	dc.b	$1F,$09,$00,$3A,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 115 "NRUSH-Bells ": FM
	dc.b	0
	dc.b	$00,$00,$3F,$40,$41,$00,$1F,$13
	dc.b	$05,$F5,$42,$04,$9F,$0D,$09,$F2
	dc.b	$28,$02,$1F,$14,$04,$F5,$41,$00
	dc.b	$1F,$0D,$09,$F2,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 116 "NRUSH - Analog Solo": FM
	dc.b	0
	dc.b	$09,$00,$04,$81,$01,$11,$53,$91
	dc.b	$09,$69,$00,$19,$81,$93,$02,$08
	dc.b	$70,$0B,$1E,$85,$00,$48,$60,$09
	dc.b	$1F,$07,$00,$08,$31,$3B,$2B,$78
	dc.b	$08,$4E,$33,$00,$0F,$00
* Patch 117 "NRUSH - Open hat": FM
	dc.b	0
	dc.b	$0C,$00,$31,$75,$2F,$06,$5F,$0B
	dc.b	$0D,$81,$7D,$02,$99,$05,$02,$71
	dc.b	$0F,$01,$9F,$05,$02,$53,$33,$05
	dc.b	$9F,$0F,$01,$AA,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 118 "NRUSH-Analog Pad 2": FM
	dc.b	0
	dc.b	$09,$00,$13,$C2,$52,$14,$02,$87
	dc.b	$00,$0C,$51,$17,$86,$0C,$00,$1C
	dc.b	$14,$2C,$12,$82,$00,$1C,$11,$19
	dc.b	$0C,$10,$00,$0C,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 119 "NRUSH-bass.thick": FM
	dc.b	0
	dc.b	$02,$00,$04,$C0,$30,$16,$1A,$0F
	dc.b	$09,$21,$70,$16,$1A,$0F,$09,$21
	dc.b	$30,$00,$1F,$08,$09,$29,$70,$00
	dc.b	$1F,$08,$09,$29,$00,$00,$00,$00
	dc.b	$00,$00,$00,$00,$0F,$00
* Patch 120 "NRUSH-bass2.slap": FM
	dc.b	0
	dc.b	$00,$00,$25,$F5,$00,$13,$1F,$00
	dc.b	$00,$05,$00,$04,$1F,$1F,$0C,$08
	dc.b	$00,$11,$1F,$11,$10,$28,$00,$00
	dc.b	$1E,$11,$13,$2B,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 121 "NRUSH-Thin Cl. Hat ": FM
	dc.b	0
	dc.b	$08,$40,$24,$C0,$3F,$08,$5F,$0F
	dc.b	$1C,$84,$1F,$00,$DC,$80,$00,$04
	dc.b	$7C,$00,$DF,$80,$10,$49,$70,$06
	dc.b	$DF,$11,$10,$49,$20,$75,$20,$5F
	dc.b	$20,$5E,$20,$00,$0F,$00
* Patch 122 "NRUSH-Jazz Guitar": FM
	dc.b	0
	dc.b	$0C,$00,$12,$C0,$31,$20,$D8,$00
	dc.b	$0B,$5C,$11,$32,$D5,$05,$14,$34
	dc.b	$31,$10,$D6,$08,$00,$2F,$00,$09
	dc.b	$96,$07,$06,$29,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 123 "NRUSH-Vibes-bright ": FM
	dc.b	0
	dc.b	$09,$00,$00,$F0,$72,$08,$53,$01
	dc.b	$1B,$40,$35,$22,$1D,$0F,$1F,$F3
	dc.b	$70,$11,$5B,$03,$1D,$03,$71,$05
	dc.b	$1F,$80,$0B,$06,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0F,$00
* Patch 124 "NRUSH-Section Strings22": FM
	dc.b	0
	dc.b	$0B,$00,$3B,$63,$33,$17,$1E,$18
	dc.b	$0C,$68,$30,$11,$14,$1C,$05,$24
	dc.b	$72,$19,$13,$1F,$06,$38,$00,$08
	dc.b	$0F,$01,$1F,$A6,$1F,$FF,$1F,$FF
	dc.b	$1F,$FF,$1F,$FF,$0E,$00
* Patch 125 "PSG-Whip Snare": PSG Noise
	dc.b	3
	dc.b	$0B,$FF,$1F,$C0,$14,$19
* Patch 126 "PSG analog bell": PSG Tone
	dc.b	2
	dc.b	$09,$FF,$12,$C0,$FF,$1D
* Patch 127 "All Digital Samples": DIG
	dc.b	1
	dc.b	$04
