	dc.b	37		; number of sequences is 37
	dc.b	'NRUSH-GLACIAL'	; name of sequence 0
	dc.b	'NRUSH-OPENING'	; name of sequence 1
	dc.b	'NRUSH-DESERT'	; name of sequence 2
	dc.b	'<UNUSED #3>'	; name of sequence 3
	dc.b	'NRUSH-WIN'	; name of sequence 4
	dc.b	'NRUSH-LOOSE'	; name of sequence 5
	dc.b	'NRUSH-EXTRA3'	; name of sequence 6
	dc.b	'NRUSH-FOREST'	; name of sequence 7
	dc.b	'NRUSH-PLAINS'	; name of sequence 8
	dc.b	'<UNUSED #9>'	; name of sequence 9
	dc.b	'NRUSH-TITLE'	; name of sequence 10
	dc.b	'<UNUSED #11>'	; name of sequence 11
	dc.b	'<UNUSED #12>'	; name of sequence 12
	dc.b	'<UNUSED #13>'	; name of sequence 13
	dc.b	'<UNUSED #14>'	; name of sequence 14
	dc.b	'<UNUSED #15>'	; name of sequence 15
	dc.b	'BIG EXPLOSION'	; name of sequence 16
	dc.b	'LEFT MISSLE'	; name of sequence 17
	dc.b	'BUTTON ACTIVATED'	; name of sequence 18
	dc.b	'CANNISTER PICKUP'	; name of sequence 19
	dc.b	'LEVEL FINISHED'	; name of sequence 20
	dc.b	'GAME OVER'	; name of sequence 21
	dc.b	'ENTER LEVEL'	; name of sequence 22
	dc.b	'BUTTON DEPRESSED'	; name of sequence 23
	dc.b	'RIGHT MISSLE'	; name of sequence 24
	dc.b	'PLAYER SHIP HIT'	; name of sequence 25
	dc.b	'CANNISTER COLLECTED'	; name of sequence 26
	dc.b	'FUEL LOW'	; name of sequence 27
	dc.b	'GAME OVER'	; name of sequence 28
	dc.b	'LASERS DESTROYED'	; name of sequence 29
	dc.b	'MISSLES DEPLEATED'	; name of sequence 30
	dc.b	'MISSION SUCCESFULL'	; name of sequence 31
	dc.b	'NUCLEAR RUSH!'	; name of sequence 32
	dc.b	'RADAR DESTROYED'	; name of sequence 33
	dc.b	'SHIELDS DESTROYED'	; name of sequence 34
	dc.b	'TANK IN ZONE'	; name of sequence 35
	dc.b	'ZONE SHIELD HIT'	; name of sequence 36
