**************************************************************************
**                              VARIABLES                                *
**************************************************************************

	XREF	VDPSlaves
	XREF	VDP_ModeSet1
	XREF	VDP_ModeSet2
	XREF	VDP_PatternA
	XREF	VDP_Window
	XREF	VDP_PatternB
	XREF	VDP_SpriteAttr
	XREF	VDP_Reg6
	XREF	VDP_BackCol
	XREF	VDP_Reg8
	XREF	VDP_Reg9
	XREF	VDP_HIntReg
	XREF	VDP_ModeSet3
	XREF	VDP_ModeSet4
	XREF	VDP_HScroll
	XREF	VDP_Reg14
	XREF	VDP_AutoInc
	XREF	VDP_ScrollSize
	XREF	VDP_WindowHPos
	XREF	VDP_WindowVPos
	XREF	DMASlaves
	XREF	VDP_DMALenLo
	XREF	VDP_DMALenHi
	XREF	VDP_DMASrcLo
	XREF	VDP_DMASrcMid
	XREF	VDP_DMASrcHi
	XREF	FlyBackFlag
	XREF	KeyHit
	XREF	KeyTab1
	XREF	KeyTab2
	XREF	CellMapCols
	XREF	CellMapRows
	XREF	DMATemp
	XREF	PalBuffer
	XREF	PalTemp
